In [1]:
import os, math, sys
import pandas as pd
import pandapower as pp
import numpy as np

from pandapower.file_io import from_json, to_json
import pandapower.networks as nw
from pandapower.timeseries import DFData

main_dir = os.path.abspath(os.path.join(os.path.abspath(""), ".."))
data_dir = os.path.join(main_dir, 'Modified_116_LV_CSV')

if main_dir not in sys.path:
    sys.path.insert(0, main_dir)

load c:\Users\vitor\AppData\Local\Programs\Python\Python312\Lib\site-packages\ortools\.libs\zlib1.dll...
load c:\Users\vitor\AppData\Local\Programs\Python\Python312\Lib\site-packages\ortools\.libs\abseil_dll.dll...
load c:\Users\vitor\AppData\Local\Programs\Python\Python312\Lib\site-packages\ortools\.libs\utf8_validity.dll...
load c:\Users\vitor\AppData\Local\Programs\Python\Python312\Lib\site-packages\ortools\.libs\re2.dll...
load c:\Users\vitor\AppData\Local\Programs\Python\Python312\Lib\site-packages\ortools\.libs\libprotobuf.dll...
load c:\Users\vitor\AppData\Local\Programs\Python\Python312\Lib\site-packages\ortools\.libs\highs.dll...
load c:\Users\vitor\AppData\Local\Programs\Python\Python312\Lib\site-packages\ortools\.libs\ortools.dll...

In [2]:
from pandapower import pp_dir

parent = os.path.join(pp_dir,'test','test_files')
path = os.path.join(parent, "European_LV_CSV")
load_path = os.path.join(data_dir, "Load Profiles")

print(load_path)

def remove_comments(f):
    '''Pass comments'''
    start=f.seek(0)
    for index in range(5):
        start=f.tell()
        if f.readline().startswith('#'):
            continue
        else:
            break      
    f.seek(start)
    return f

load_xlsx = os.path.join(data_dir, "Loads.xlsx")
loads = pd.read_excel(os.path.join(data_dir, "Loads.xlsx"), skiprows=2)
loads.Bus = [math.floor(l) for l in loads.Bus]

load_shapes = os.path.join(data_dir, "LoadShapes.csv")    
    
with open (load_shapes,'r') as f:
    f = remove_comments(f)
    loadshapes = pd.read_csv(f, sep=';')
    f.close()

c:\Users\vitor\Documents\IST-thesis-hosting-capacity\Modified_116_LV_CSV\Load Profiles

In [3]:
net_off_peak_1 = nw.ieee_european_lv_asymmetric('off_peak_1')
net_on_peak_566 = nw.ieee_european_lv_asymmetric('on_peak_566')
net_off_peak_1440 = nw.ieee_european_lv_asymmetric('off_peak_1440')

In [4]:
net_off_peak_1.asymmetric_load[['p_a_mw', 'q_a_mvar', 'p_b_mw', 'q_b_mvar', 'p_c_mw', 'q_c_mvar']].describe()

          p_a_mw   q_a_mvar     p_b_mw      q_b_mvar     p_c_mw      q_c_mvar
count  55.000000  55.000000  55.000000  5.500000e+01  55.000000  5.500000e+01
mean    0.000019   0.000006   0.000017  5.533845e-09   0.000015  4.870501e-09
std     0.000025   0.000008   0.000024  7.820350e-09   0.000026  8.457090e-09
min     0.000000   0.000000   0.000000  0.000000e+00   0.000000  0.000000e+00
25%     0.000000   0.000000   0.000000  0.000000e+00   0.000000  0.000000e+00
50%     0.000000   0.000000   0.000000  0.000000e+00   0.000000  0.000000e+00
75%     0.000049   0.000016   0.000045  1.462644e-08   0.000036  1.166829e-08
max     0.000062   0.000020   0.000057  1.873499e-08   0.000092  3.023894e-08

In [5]:
net_on_peak_566.asymmetric_load[['p_a_mw', 'q_a_mvar', 'p_b_mw', 'q_b_mvar', 'p_c_mw', 'q_c_mvar']].describe()

          p_a_mw   q_a_mvar     p_b_mw      q_b_mvar     p_c_mw      q_c_mvar
count  55.000000  55.000000  55.000000  5.500000e+01  55.000000  5.500000e+01
mean    0.000317   0.000104   0.000613  2.013818e-07   0.000113  3.719509e-08
std     0.001457   0.000479   0.001939  6.372184e-07   0.000401  1.318596e-07
min     0.000000   0.000000   0.000000  0.000000e+00   0.000000  0.000000e+00
25%     0.000000   0.000000   0.000000  0.000000e+00   0.000000  0.000000e+00
50%     0.000000   0.000000   0.000000  0.000000e+00   0.000000  0.000000e+00
75%     0.000054   0.000018   0.000164  5.406854e-08   0.000037  1.199697e-08
max     0.010471   0.003442   0.012659  4.160812e-06   0.002836  9.321481e-07

In [6]:
net_off_peak_1440.asymmetric_load[['p_a_mw', 'q_a_mvar', 'p_b_mw', 'q_b_mvar', 'p_c_mw', 'q_c_mvar']].describe()

          p_a_mw   q_a_mvar     p_b_mw      q_b_mvar     p_c_mw      q_c_mvar
count  55.000000  55.000000  55.000000  5.500000e+01  55.000000  5.500000e+01
mean    0.000067   0.000022   0.000066  2.184255e-08   0.000042  1.394816e-08
std     0.000156   0.000051   0.000185  6.093746e-08   0.000115  3.775719e-08
min     0.000000   0.000000   0.000000  0.000000e+00   0.000000  0.000000e+00
25%     0.000000   0.000000   0.000000  0.000000e+00   0.000000  0.000000e+00
50%     0.000000   0.000000   0.000000  0.000000e+00   0.000000  0.000000e+00
75%     0.000050   0.000017   0.000046  1.511947e-08   0.000038  1.249000e-08
max     0.000823   0.000271   0.001042  3.424888e-07   0.000561  1.843918e-07

In [7]:
def create_data_source(data_dir, **kwargs):
    """
    Loads and processes profile data based on loads and shapes from Excel/CSV files.

    Parameters:
    - network: Placeholder for a network object (not used in current function).
    - kwargs: Dictionary of file directories. Must include:
        - 'data_dir': Directory containing 'Loads.xlsx' and 'LoadShapes.csv'
        - 'profile_dir': Directory containing the individual profile CSV files

    Returns:
    - profile_df (pd.DataFrame): DataFrame with timeseries profile data
    """

    profile_dir = kwargs.get('profile_dir')
    ds_index = kwargs.get('ds_index')
    ds_index = False if ds_index is None else ds_index

    if not data_dir or not profile_dir:
        raise ValueError("Missing data directory path(s)")
    if os.path.exists(os.path.join(data_dir, 'profile_datasource.csv')):
        profile_df = pd.read_csv(os.path.join(data_dir, 'profile_datasource.csv'), index_col=0)
    else:
        # Read Excel and CSV files
        loads_df = pd.read_excel(os.path.join(data_dir, "Loads.xlsx"), skiprows=2)
        loadShape_df = pd.read_csv(os.path.join(data_dir, 'LoadShapes.csv'), skiprows=1, sep=';')

        # Merge the dataframes
        merged_load = loads_df.merge(loadShape_df, left_on="Yearly", right_on="Name", how="left")

        # Load individual time series profiles
        ts_data = {}
        for _, row in merged_load.iterrows():
            # print(row["File"])
            file_path = os.path.join(profile_dir, row["File"])
            try:
                profile = pd.read_csv(file_path)
                ts_data[row["Name_x"]] = profile["mult"].values * 1e-3 # or .to_numpy()
                ts_data[row["Name_x"]+'_Q'] = profile["mult"].values * 1e-3 * np.tan(
                    np.arccos(float(row['PF']))
                )
            except:
                profile = pd.read_csv(file_path, sep=';')
                ts_data[row["Name_x"]] = profile["mult"].values * 1e-3 # or .to_numpy()
                ts_data[row["Name_x"]+'_Q'] = profile["mult"].values * 1e-3 * np.tan(
                    np.arccos(float(row['PF']))
                )

        # Create DataFrame and save it
        profile_df = pd.DataFrame(ts_data, index=profile.time if ds_index else None)
        profile_df.to_csv(os.path.join(data_dir, 'profile_datasource.csv'), index=True)

    return profile_df, DFData(profile_df)

profile_df, ds = create_data_source(data_dir, profile_dir=os.path.join(data_dir, 'Load Profiles'), ds_index=True)
profile_df

,LOAD1,LOAD1_Q,LOAD2,LOAD2_Q,LOAD3,LOAD3_Q,LOAD4,LOAD4_Q,LOAD5,LOAD5_Q,...,LOAD51,LOAD51_Q,LOAD52,LOAD52_Q,LOAD53,LOAD53_Q,LOAD54,LOAD54_Q,LOAD55,LOAD55_Q
time,,,,,,,,,,,,,,,,,,,,,
00:01:00,0.000036,0.000012,0.000044,0.000014,0.000054,0.000018,0.000048,0.000016,0.000035,0.000012,...,0.000053,0.000017,0.000052,0.000017,0.000047,0.000015,0.000048,0.000016,0.000055,0.000018
00:02:00,0.000036,0.000012,0.000044,0.000014,0.000054,0.000018,0.000048,0.000016,0.000035,0.000012,...,0.000053,0.000017,0.000052,0.000017,0.000047,0.000015,0.000048,0.000016,0.000055,0.000018
00:03:00,0.000036,0.000012,0.000044,0.000014,0.000054,0.000018,0.000048,0.000016,0.000035,0.000012,...,0.000053,0.000017,0.000052,0.000017,0.000047,0.000015,0.000057,0.000019,0.000055,0.000018
00:04:00,0.000036,0.000012,0.000044,0.000014,0.000054,0.000018,0.000227,0.000075,0.000035,0.000012,...,0.000053,0.000017,0.000052,0.000017,0.000047,0.000015,0.000048,0.000016,0.000055,0.000018
00:05:00,0.000036,0.000012,0.000044,0.000014,0.000054,0.000018,0.000227,0.000075,0.000035,0.000012,...,0.000053,0.000017,0.000052,0.000017,0.000047,0.000015,0.000048,0.000016,0.000055,0.000018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23:56:00,0.000036,0.000012,0.001136,0.000373,0.000548,0.000180,0.000048,0.000016,0.000347,0.000114,...,0.000053,0.000017,0.000217,0.000071,0.000047,0.000015,0.000048,0.000016,0.000055,0.000018
23:57:00,0.000036,0.000012,0.001136,0.000373,0.000548,0.000180,0.000048,0.000016,0.000347,0.000114,...,0.000053,0.000017,0.000544,0.000179,0.000047,0.000015,0.000048,0.000016,0.000055,0.000018
23:58:00,0.000036,0.000012,0.000982,0.000323,0.000561,0.000184,0.000048,0.000016,0.000347,0.000114,...,0.000053,0.000017,0.000544,0.000179,0.000047,0.000015,0.000048,0.000016,0.000055,0.000018
23:59:00,0.000036,0.000012,0.000982,0.000323,0.000471,0.000155,0.000048,0.000016,0.000347,0.000114,...,0.000053,0.000017,0.000544,0.000179,0.000047,0.000015,0.000048,0.000016,0.000055,0.000018
24:00:00,0.000036,0.000012,0.001042,0.000342,0.000504,0.000166,0.000048,0.000016,0.000347,0.000114,...,0.000053,0.000017,0.000544,0.000179,0.000047,0.000015,0.000048,0.000016,0.000055,0.000018

In [8]:
net_off_peak_1 = nw.ieee_european_lv_asymmetric('off_peak_1')
net_on_peak_566 = nw.ieee_european_lv_asymmetric('on_peak_566')
net_off_peak_1440 = nw.ieee_european_lv_asymmetric('off_peak_1440')
try:
    pp.runpp_3ph(net_off_peak_1)
    print('runnpp_3ph on net_off_peak_1 successful!')
    pp.runpp_3ph(net_on_peak_566)
    print('runnpp_3ph on net_on_peak_566 successful!')
    pp.runpp_3ph(net_off_peak_1440)
    print('runnpp_3ph on net_off_peak_1440 successful!')
except Exception as e:
    print(e)

runnpp_3ph on net_off_peak_1 successful!
runnpp_3ph on net_on_peak_566 successful!
runnpp_3ph on net_off_peak_1440 successful!

In [9]:
from copy import deepcopy
import create_basic_network as cbn
import pandapower.control as ppc
# print(cbn.net)
net = deepcopy(cbn.net)
pp.runpp_3ph(net, init='auto', max_iteration=100, tolerance_mva=1e-5, calc_voltage_angles=True, v_debug=True)

for _, row in loads.iterrows():
    bus_id = math.floor(row['Bus'])
    pa = qa = pb = qb = pc = qc = 0

    if (bus_id in net.bus.name) and (row['phases'] in {'A', 'B', 'C'}):
        if row['phases'] == 'A':
            pa = row['kW']
            qa = row['kW'] * np.tan(np.arccos(row['PF']))
        elif row['phases'] == 'B':
            pb = row['kW']
            qb = row['kW'] * np.tan(np.arccos(row['PF']))
        else:  # 'C'
            pc = row['kW']
            qc = row['kW'] * np.tan(np.arccos(row['PF']))

        load = pp.create_asymmetric_load(
            net, bus=net.bus.index[net.bus.name == bus_id][0],
            p_a_mw=pa / 1000, q_a_mvar=qa / 1000,
            p_b_mw=pb / 1000, q_b_mvar=qb / 1000,
            p_c_mw=pc / 1000, q_c_mvar=qc / 1000,
            name=row['Name']
        )

        # Attach ConstControl
        phase = row['phases'].lower()
        ppc.ConstControl(
            net, element_index=load,
            variable=f"p_{phase}_mw",
            element="asymmetric_load",
            profile_name=row['Name'], data_source=ds
        )

orig_bus = net.asymmetric_load.bus
net.asymmetric_load = net_off_peak_1440.asymmetric_load
net.asymmetric_load.bus = orig_bus
net.asymmetric_load

Created External Grid!
Created Transformer!
Created Shunt!
Created 117 Buses!
Created 115 Lines!

Debugging successful!
This pandapower network includes the following parameter tables:
   - bus (117 elements)
   - shunt (1 element)
   - ext_grid (1 element)
   - line (115 elements)
   - trafo (1 element)
 and the following results tables:
   - res_bus_3ph (117 elements)
   - res_line_3ph (115 elements)
   - res_trafo_3ph (1 element)
   - res_ext_grid_3ph (1 element)
   - res_shunt_3ph (1 element)

,name,bus,p_a_mw,q_a_mvar,p_b_mw,q_b_mvar,p_c_mw,q_c_mvar,sn_mva,scaling,in_service,type,description,sernum,for_name,chr_name
0,LOAD1,5,0.000036,0.000012,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
1,LOAD2,7,0.000000,0.000000,0.001042,3.424888e-07,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
2,LOAD3,10,0.000504,0.000166,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
3,LOAD4,11,0.000048,0.000016,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
4,LOAD5,12,0.000347,0.000114,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
5,LOAD6,13,0.000000,0.000000,0.000052,1.709157e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
6,LOAD7,21,0.000000,0.000000,0.000055,1.807763e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
7,LOAD8,25,0.000000,0.000000,0.000000,0.000000e+00,0.000561,1.843918e-07,NaN,1.0,True,wye,,,,
8,LOAD9,26,0.000281,0.000092,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
9,LOAD10,29,0.000000,0.000000,0.000057,1.873499e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
10,LOAD11,30,0.000000,0.000000,0.000049,1.610552e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
11,LOAD12,33,0.000000,0.000000,0.000000,0.000000e+00,0.000469,1.541528e-07,NaN,1.0,True,wye,,,,
12,LOAD13,34,0.000000,0.000000,0.000056,1.840631e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
13,LOAD14,37,0.000210,0.000069,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
14,LOAD15,39,0.000000,0.000000,0.000053,1.742026e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
15,LOAD16,40,0.000000,0.000000,0.000000,0.000000e+00,0.000052,1.709157e-08,NaN,1.0,True,wye,,,,
16,LOAD17,42,0.000000,0.000000,0.000000,0.000000e+00,0.000048,1.577684e-08,NaN,1.0,True,wye,,,,
17,LOAD18,45,0.000000,0.000000,0.000000,0.000000e+00,0.000049,1.610552e-08,NaN,1.0,True,wye,,,,
18,LOAD19,46,0.000000,0.000000,0.000000,0.000000e+00,0.000053,1.742026e-08,NaN,1.0,True,wye,,,,
19,LOAD20,47,0.000051,0.000017,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
20,LOAD21,49,0.000045,0.000015,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
21,LOAD22,50,0.000054,0.000018,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
22,LOAD23,52,0.000000,0.000000,0.000604,1.985252e-07,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
23,LOAD24,54,0.000000,0.000000,0.000000,0.000000e+00,0.000054,1.774894e-08,NaN,1.0,True,wye,,,,
24,LOAD25,57,0.000050,0.000016,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
25,LOAD26,60,0.000000,0.000000,0.000034,1.117526e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
26,LOAD27,62,0.000000,0.000000,0.000000,0.000000e+00,0.000155,5.094603e-08,NaN,1.0,True,wye,,,,
27,LOAD28,64,0.000000,0.000000,0.000000,0.000000e+00,0.000028,9.203155e-09,NaN,1.0,True,wye,,,,
28,LOAD29,66,0.000823,0.000271,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
29,LOAD30,67,0.000053,0.000017,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
30,LOAD31,72,0.000182,0.000060,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
31,LOAD32,73,0.000000,0.000000,0.000000,0.000000e+00,0.000056,1.840631e-08,NaN,1.0,True,wye,,,,
32,LOAD33,75,0.000000,0.000000,0.000000,0.000000e+00,0.000250,8.217103e-08,NaN,1.0,True,wye,,,,
33,LOAD34,76,0.000176,0.000058,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
34,LOAD35,77,0.000000,0.000000,0.000043,1.413342e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
35,LOAD36,80,0.000000,0.000000,0.000055,1.807763e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
36,LOAD37,81,0.000000,0.000000,0.000045,1.479078e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
37,LOAD38,83,0.000000,0.000000,0.000228,7.493998e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
38,LOAD39,87,0.000000,0.000000,0.000000,0.000000e+00,0.000048,1.577684e-08,NaN,1.0,True,wye,,,,
39,LOAD40,88,0.000000,0.000000,0.000043,1.413342e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
40,LOAD41,93,0.000000,0.000000,0.000196,6.442208e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
41,LOAD42,95,0.000000,0.000000,0.000000,0.000000e+00,0.000054,1.774894e-08,NaN,1.0,True,wye,,,,
42,LOAD43,96,0.000000,0.000000,0.000000,0.000000e+00,0.000050,1.643420e-08,NaN,1.0,True,wye,,,,
43,LOAD44,97,0.000000,0.000000,0.000029,9.531839e-09,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
44,LOAD45,102,0.000000,0.000000,0.000657,2.159455e-07,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
45,LOAD46,103,0.000049,0.000016,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
46,LOAD47,104,0.000000,0.000000,0.000000,0.000000e+00,0.000407,1.337744e-07,NaN,1.0,True,wye,,,,
47,LOAD48,106,0.000046,0.000015,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
48,LOAD49,107,0.000054,0.000018,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
49,LOAD50,110,0.000000,0.000000,0.000310,1.018921e-07,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
50,LOAD51,112,0.000053,0.000017,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
51,LOAD52,113,0.000544,0.000179,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
52,LOAD53,114,0.000000,0.000000,0.000047,1.544815e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
53,LOAD54,115,0.000048,0.000016,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
54,LOAD55,116,0.000055,0.000018,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,

In [10]:
net_off_peak_1440.trafo
for c in net_off_peak_1440.trafo.columns:
    # print(f"{c} = {net_off_peak_1440.trafo.at[0, c]}")
    net.trafo[c] = net_off_peak_1440.trafo.at[0, c]

net.trafo.name=cbn.trafo_dict['Name']
net.trafo.std_type=None
net.trafo.hv_bus=cbn.hv_bus
net.trafo.lv_bus=cbn.lv_bus
net.trafo.sn_mva=cbn.trafo_dict[' MVA']
net.trafo.vn_hv_kv=cbn.trafo_dict[' kV_pri']
net.trafo.vn_lv_kv=cbn.trafo_dict[' kV_sec']
net.trafo.vk_percent=cbn.trafo_dict[' %XHL']
net.trafo.vkr_percent=cbn.trafo_dict['% resistance']
net.trafo.vk0_percent=cbn.trafo_dict[' %XHL']
net.trafo.vkr0_percent=cbn.trafo_dict['% resistance']
net.trafo

,name,std_type,hv_bus,lv_bus,sn_mva,vn_hv_kv,vn_lv_kv,vk_percent,vkr_percent,pfe_kw,...,vkr0_percent,mag0_percent,mag0_rx,si0_hv_partial,vector_group,xn_ohm,k_st,tap_set_vm_pu,description,equipment
0,TR1,None,0,1,0.8,11,0.416,4,0.4,0.0,...,0.4,1,0,0.9,Dyn,0.0,1.0,1.0,,

In [11]:
net.line.describe()

,from_bus,to_bus,length_km,r_ohm_per_km,x_ohm_per_km,c_nf_per_km,g_us_per_km,max_i_ka,df,parallel,r0_ohm_per_km,x0_ohm_per_km,c0_nf_per_km,g0_us_per_km
count,115.000000,115.000000,115.000000,115.000000,115.000000,115.0,115.0,115.000000,115.0,115.0,115.000000,115.000000,115.0,115.0
mean,53.530435,59.000000,0.010311,0.866948,0.082543,0.0,0.0,0.290241,1.0,1.0,1.173487,0.086374,0.0,0.0
std,32.867710,33.341666,0.005717,0.402012,0.007552,0.0,0.0,0.061675,0.0,0.0,0.280478,0.004277,0.0,0.0
min,1.000000,2.000000,0.002191,0.089000,0.067500,0.0,0.0,0.217697,1.0,1.0,0.319000,0.076000,0.0,0.0
25%,23.000000,30.500000,0.006411,0.469000,0.075000,0.0,0.0,0.247626,1.0,1.0,1.200000,0.086500,0.0,0.0
50%,55.000000,59.000000,0.009339,1.150000,0.088000,0.0,0.0,0.247626,1.0,1.0,1.200000,0.088000,0.0,0.0
75%,83.000000,87.500000,0.013668,1.150000,0.088000,0.0,0.0,0.350505,1.0,1.0,1.200000,0.088000,0.0,0.0
max,111.000000,116.000000,0.037663,1.257000,0.092000,0.0,0.0,0.407240,1.0,1.0,1.581000,0.093000,0.0,0.0

In [12]:
net_off_peak_1440.line.describe()

,from_bus,to_bus,length_km,r_ohm_per_km,x_ohm_per_km,c_nf_per_km,g_us_per_km,max_i_ka,df,parallel,alpha,temperature_degree_celsius,line_idx,section_idx,c0_nf_per_km
count,905.000000,905.000000,905.000000,905.000000,905.000000,905.0,905.0,905.000,905.0,905.0,905.00000,905.0,905.000000,905.0,905.0
mean,447.148066,454.000000,0.001582,0.936211,0.082113,0.0,0.0,0.421,1.0,1.0,0.00403,80.0,452.000000,0.0,0.0
std,260.961298,261.395295,0.002222,0.737723,0.008423,0.0,0.0,0.000,0.0,0.0,0.00000,0.0,261.395295,0.0,0.0
min,1.000000,2.000000,0.000034,0.089000,0.067500,0.0,0.0,0.421,1.0,1.0,0.00403,80.0,0.000000,0.0,0.0
25%,220.000000,228.000000,0.000168,0.469000,0.075000,0.0,0.0,0.421,1.0,1.0,0.00403,80.0,226.000000,0.0,0.0
50%,446.000000,454.000000,0.000487,1.150000,0.088000,0.0,0.0,0.421,1.0,1.0,0.00403,80.0,452.000000,0.0,0.0
75%,673.000000,680.000000,0.002275,1.150000,0.088000,0.0,0.0,0.421,1.0,1.0,0.00403,80.0,678.000000,0.0,0.0
max,905.000000,906.000000,0.011977,3.970000,0.099000,0.0,0.0,0.421,1.0,1.0,0.00403,80.0,904.000000,0.0,0.0

In [13]:
net.line['alpha']=net_off_peak_1440.line['alpha']
net.line['temperature_degree_celsius']=net_off_peak_1440.line['temperature_degree_celsius']
net.line

,name,std_type,from_bus,to_bus,length_km,r_ohm_per_km,x_ohm_per_km,c_nf_per_km,g_us_per_km,max_i_ka,...,parallel,type,in_service,geo,r0_ohm_per_km,x0_ohm_per_km,c0_nf_per_km,g0_us_per_km,alpha,temperature_degree_celsius
0,LINE1,None,1,2,0.021867,0.446,0.071,0.0,0.0,0.344259,...,1,cs,True,None,1.505,0.083,0.0,0.0,0.00403,80.0
1,LINE2,None,2,3,0.005905,1.150,0.088,0.0,0.0,0.247626,...,1,cs,True,None,1.200,0.088,0.0,0.0,0.00403,80.0
2,LINE3,None,2,4,0.012622,0.446,0.071,0.0,0.0,0.344259,...,1,cs,True,None,1.505,0.083,0.0,0.0,0.00403,80.0
3,LINE4,None,3,5,0.005351,1.150,0.088,0.0,0.0,0.247626,...,1,cs,True,None,1.200,0.088,0.0,0.0,0.00403,80.0
4,LINE5,None,3,10,0.006747,1.150,0.088,0.0,0.0,0.247626,...,1,cs,True,None,1.200,0.088,0.0,0.0,0.00403,80.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,LINE111,None,99,109,0.010772,1.150,0.088,0.0,0.0,0.247626,...,1,cs,True,None,1.200,0.088,0.0,0.0,0.00403,80.0
111,LINE112,None,108,110,0.007508,1.257,0.085,0.0,0.0,0.217697,...,1,cs,True,None,1.257,0.085,0.0,0.0,0.00403,80.0
112,LINE113,None,108,114,0.009339,1.257,0.085,0.0,0.0,0.217697,...,1,cs,True,None,1.257,0.085,0.0,0.0,0.00403,80.0
113,LINE114,None,109,113,0.010336,0.868,0.092,0.0,0.0,0.315840,...,1,cs,True,None,0.760,0.092,0.0,0.0,0.00403,80.0
114,LINE115,None,109,116,0.008092,1.150,0.088,0.0,0.0,0.247626,...,1,cs,True,None,1.200,0.088,0.0,0.0,0.00403,80.0

In [14]:
net_off_peak_1440

This pandapower network includes the following parameter tables:
   - bus (907 elements)
   - asymmetric_load (55 elements)
   - ext_grid (1 element)
   - line (905 elements)
   - trafo (1 element)
 and the following results tables:
   - res_bus (907 elements)
   - res_line (905 elements)
   - res_trafo (1 element)
   - res_ext_grid (1 element)
   - res_bus_3ph (907 elements)
   - res_line_3ph (905 elements)
   - res_trafo_3ph (1 element)
   - res_ext_grid_3ph (1 element)
   - res_asymmetric_load_3ph (55 elements)

In [15]:
net.controller.drop(net.controller.index, inplace=True)
net

This pandapower network includes the following parameter tables:
   - bus (117 elements)
   - asymmetric_load (55 elements)
   - shunt (1 element)
   - ext_grid (1 element)
   - line (115 elements)
   - trafo (1 element)
 and the following results tables:
   - res_bus_3ph (117 elements)
   - res_line_3ph (115 elements)
   - res_trafo_3ph (1 element)
   - res_ext_grid_3ph (1 element)
   - res_shunt_3ph (1 element)

In [16]:
net_off_peak_1440.ext_grid

for c in net_off_peak_1440.trafo.columns:
    print(f"{c}:\t original = {net.trafo.at[0, c]} | nw = {net_off_peak_1440.trafo.at[0, c]}")
#     net.trafo[c] = net_off_peak_1440.trafo.at[0, c]

name:	 original = TR1 | nw = Trafo
std_type:	 original = None | nw = 08 MVA 10/04 kV Dyn1 ASEA
hv_bus:	 original = 0 | nw = 0
lv_bus:	 original = 1 | nw = 1
sn_mva:	 original = 0.8 | nw = 0.800000011920929
vn_hv_kv:	 original = 11 | nw = 11.0
vn_lv_kv:	 original = 0.416 | nw = 0.416000008583069
vk_percent:	 original = 4 | nw = 4.019950389862061
vkr_percent:	 original = 0.4 | nw = 0.400000005960464
pfe_kw:	 original = 0.0 | nw = 0.0
i0_percent:	 original = 0.0 | nw = 0.0
shift_degree:	 original = 30.0 | nw = 30.0
tap_side:	 original = hv | nw = hv
tap_neutral:	 original = 0 | nw = 0
tap_min:	 original = -2 | nw = -2
tap_max:	 original = 2 | nw = 2
tap_step_percent:	 original = 2.5 | nw = 2.5
tap_step_degree:	 original = 0.0 | nw = 0.0
tap_pos:	 original = 0 | nw = 0
parallel:	 original = 1 | nw = 1
df:	 original = 1.0 | nw = 1.0
in_service:	 original = True | nw = True
tap_set_vm_pu:	 original = 1.0 | nw = 1.0
description:	 original =  | nw =
equipment:	 original =  | nw =
vector_group:	 original = Dyn | nw = Dyn
vk0_percent:	 original = 4 | nw = 4.019950389862061
vkr0_percent:	 original = 0.4 | nw = 0.400000005960464
mag0_percent:	 original = 1 | nw = 1
mag0_rx:	 original = 0 | nw = 0
si0_hv_partial:	 original = 0.899999976158142 | nw = 0.899999976158142
tap_changer_type:	 original = Ratio | nw = Ratio
xn_ohm:	 original = 0.0 | nw = 0.0
k_st:	 original = 1.0 | nw = 1.0

In [17]:
net.ext_grid

,name,bus,vm_pu,va_degree,slack_weight,in_service,controllable,roxo_min,x0x_min,x0x_max,r0x0_max,s_sc_max_mva,rx_min,rx_max
0,None,0,1.05,0.0,1.0,True,False,0.1,1.0,1.0,0.1,57.157677,0.1,0.1

In [18]:
pp.runpp_3ph(net, init='auto', max_iteration=100, tolerance_mva=1e-5, calc_voltage_angles=True, v_debug=True)
to_json(net, os.path.join(main_dir, 'json_networks', "full_load_network.json"))