In [1]:
import os, math, sys
import pandas as pd
import pandapower as pp
import numpy as np

from pandapower.file_io import from_json, to_json
import pandapower.networks as nw
from pandapower.timeseries import DFData

main_dir = os.path.abspath(os.path.join(os.path.abspath(""), ".."))
data_dir = os.path.join(main_dir, 'Modified_116_LV_CSV')

if main_dir not in sys.path:
    sys.path.insert(0, main_dir)

load c:\Users\vitor\AppData\Local\Programs\Python\Python312\Lib\site-packages\ortools\.libs\zlib1.dll...
load c:\Users\vitor\AppData\Local\Programs\Python\Python312\Lib\site-packages\ortools\.libs\abseil_dll.dll...
load c:\Users\vitor\AppData\Local\Programs\Python\Python312\Lib\site-packages\ortools\.libs\utf8_validity.dll...
load c:\Users\vitor\AppData\Local\Programs\Python\Python312\Lib\site-packages\ortools\.libs\re2.dll...
load c:\Users\vitor\AppData\Local\Programs\Python\Python312\Lib\site-packages\ortools\.libs\libprotobuf.dll...
load c:\Users\vitor\AppData\Local\Programs\Python\Python312\Lib\site-packages\ortools\.libs\highs.dll...
load c:\Users\vitor\AppData\Local\Programs\Python\Python312\Lib\site-packages\ortools\.libs\ortools.dll...

In [29]:
from pandapower import pp_dir

parent = os.path.join(pp_dir,'test','test_files')
path = os.path.join(parent, "European_LV_CSV")
load_path = os.path.join(data_dir, "Load Profiles")

print(load_path)

def remove_comments(f):
    '''Pass comments'''
    start=f.seek(0)
    for index in range(5):
        start=f.tell()
        if f.readline().startswith('#'):
            continue
        else:
            break      
    f.seek(start)
    return f

load_xlsx = os.path.join(data_dir, "Loads.xlsx")
loads = pd.read_excel(os.path.join(data_dir, "Loads.xlsx"), skiprows=2)
loads.Bus = [math.floor(l) for l in loads.Bus]

load_shapes = os.path.join(data_dir, "LoadShapes.csv")    
    
with open (load_shapes,'r') as f:
    f = remove_comments(f)
    loadshapes = pd.read_csv(f, sep=';')
    f.close()

c:\Users\vitor\OneDrive\IST Mestrado\Tese Mestrado\DEV\Modified_116_LV_CSV\Load Profiles

In [2]:
net_off_peak_1 = nw.ieee_european_lv_asymmetric('off_peak_1')
net_on_peak_566 = nw.ieee_european_lv_asymmetric('on_peak_566')
net_off_peak_1440 = nw.ieee_european_lv_asymmetric('off_peak_1440')

In [10]:
net_off_peak_1.asymmetric_load[['p_a_mw', 'q_a_mvar', 'p_b_mw', 'q_b_mvar', 'p_c_mw', 'q_c_mvar']].describe()

          p_a_mw   q_a_mvar     p_b_mw      q_b_mvar     p_c_mw      q_c_mvar
count  55.000000  55.000000  55.000000  5.500000e+01  55.000000  5.500000e+01
mean    0.000019   0.000006   0.000017  5.533845e-09   0.000015  4.870501e-09
std     0.000025   0.000008   0.000024  7.820350e-09   0.000026  8.457090e-09
min     0.000000   0.000000   0.000000  0.000000e+00   0.000000  0.000000e+00
25%     0.000000   0.000000   0.000000  0.000000e+00   0.000000  0.000000e+00
50%     0.000000   0.000000   0.000000  0.000000e+00   0.000000  0.000000e+00
75%     0.000049   0.000016   0.000045  1.462644e-08   0.000036  1.166829e-08
max     0.000062   0.000020   0.000057  1.873499e-08   0.000092  3.023894e-08

In [11]:
net_on_peak_566.asymmetric_load[['p_a_mw', 'q_a_mvar', 'p_b_mw', 'q_b_mvar', 'p_c_mw', 'q_c_mvar']].describe()

          p_a_mw   q_a_mvar     p_b_mw      q_b_mvar     p_c_mw      q_c_mvar
count  55.000000  55.000000  55.000000  5.500000e+01  55.000000  5.500000e+01
mean    0.000317   0.000104   0.000613  2.013818e-07   0.000113  3.719509e-08
std     0.001457   0.000479   0.001939  6.372184e-07   0.000401  1.318596e-07
min     0.000000   0.000000   0.000000  0.000000e+00   0.000000  0.000000e+00
25%     0.000000   0.000000   0.000000  0.000000e+00   0.000000  0.000000e+00
50%     0.000000   0.000000   0.000000  0.000000e+00   0.000000  0.000000e+00
75%     0.000054   0.000018   0.000164  5.406854e-08   0.000037  1.199697e-08
max     0.010471   0.003442   0.012659  4.160812e-06   0.002836  9.321481e-07

In [12]:
net_off_peak_1440.asymmetric_load[['p_a_mw', 'q_a_mvar', 'p_b_mw', 'q_b_mvar', 'p_c_mw', 'q_c_mvar']].describe()

          p_a_mw   q_a_mvar     p_b_mw      q_b_mvar     p_c_mw      q_c_mvar
count  55.000000  55.000000  55.000000  5.500000e+01  55.000000  5.500000e+01
mean    0.000067   0.000022   0.000066  2.184255e-08   0.000042  1.394816e-08
std     0.000156   0.000051   0.000185  6.093746e-08   0.000115  3.775719e-08
min     0.000000   0.000000   0.000000  0.000000e+00   0.000000  0.000000e+00
25%     0.000000   0.000000   0.000000  0.000000e+00   0.000000  0.000000e+00
50%     0.000000   0.000000   0.000000  0.000000e+00   0.000000  0.000000e+00
75%     0.000050   0.000017   0.000046  1.511947e-08   0.000038  1.249000e-08
max     0.000823   0.000271   0.001042  3.424888e-07   0.000561  1.843918e-07

In [32]:
def create_data_source(data_dir, **kwargs):
    """
    Loads and processes profile data based on loads and shapes from Excel/CSV files.

    Parameters:
    - network: Placeholder for a network object (not used in current function).
    - kwargs: Dictionary of file directories. Must include:
        - 'data_dir': Directory containing 'Loads.xlsx' and 'LoadShapes.csv'
        - 'profile_dir': Directory containing the individual profile CSV files

    Returns:
    - profile_df (pd.DataFrame): DataFrame with timeseries profile data
    """

    profile_dir = kwargs.get('profile_dir')
    ds_index = kwargs.get('ds_index')
    ds_index = False if ds_index is None else ds_index

    if not data_dir or not profile_dir:
        raise ValueError("Missing data directory path(s)")
    if os.path.exists(os.path.join(data_dir, 'profile_datasource.csv')):
        profile_df = pd.read_csv(os.path.join(data_dir, 'profile_datasource.csv'), index_col=0)
    else:
        # Read Excel and CSV files
        loads_df = pd.read_excel(os.path.join(data_dir, "Loads.xlsx"), skiprows=2)
        loadShape_df = pd.read_csv(os.path.join(data_dir, 'LoadShapes.csv'), skiprows=1, sep=';')

        # Merge the dataframes
        merged_load = loads_df.merge(loadShape_df, left_on="Yearly", right_on="Name", how="left")

        # Load individual time series profiles
        ts_data = {}
        for _, row in merged_load.iterrows():
            # print(row["File"])
            file_path = os.path.join(profile_dir, row["File"])
            try:
                profile = pd.read_csv(file_path)
                ts_data[row["Name_x"]] = profile["mult"].values * 1e-3 # or .to_numpy()
                ts_data[row["Name_x"]+'_Q'] = profile["mult"].values * 1e-3 * np.tan(
                    np.arccos(float(row['PF']))
                )
            except:
                profile = pd.read_csv(file_path, sep=';')
                ts_data[row["Name_x"]] = profile["mult"].values * 1e-3 # or .to_numpy()
                ts_data[row["Name_x"]+'_Q'] = profile["mult"].values * 1e-3 * np.tan(
                    np.arccos(float(row['PF']))
                )

        # Create DataFrame and save it
        profile_df = pd.DataFrame(ts_data, index=profile.time if ds_index else None)
        profile_df.to_csv(os.path.join(data_dir, 'profile_datasource.csv'), index=True)

    return profile_df, DFData(profile_df)

profile_df, ds = create_data_source(data_dir, profile_dir=os.path.join(data_dir, 'Load Profiles'), ds_index=True)
profile_df

,LOAD1,LOAD2,LOAD3,LOAD4,LOAD5,LOAD6,LOAD7,LOAD8,LOAD9,LOAD10,...,LOAD46,LOAD47,LOAD48,LOAD49,LOAD50,LOAD51,LOAD52,LOAD53,LOAD54,LOAD55
time,,,,,,,,,,,,,,,,,,,,,
00:01:00,0.000036,0.000044,0.000054,0.000048,0.000035,0.000052,0.000055,0.000043,0.000059,0.000057,...,0.000062,0.000045,0.000046,0.000054,0.000052,0.000053,0.000052,0.000047,0.000048,0.000055
00:02:00,0.000036,0.000044,0.000054,0.000048,0.000035,0.000052,0.000055,0.000043,0.000059,0.000057,...,0.000062,0.000045,0.000046,0.000054,0.000052,0.000053,0.000052,0.000047,0.000048,0.000055
00:03:00,0.000036,0.000044,0.000054,0.000048,0.000035,0.000052,0.000055,0.000043,0.000059,0.000057,...,0.000122,0.000045,0.000046,0.000054,0.000052,0.000053,0.000052,0.000047,0.000057,0.000055
00:04:00,0.000036,0.000044,0.000054,0.000227,0.000035,0.000052,0.000055,0.000043,0.000059,0.000057,...,0.000162,0.000045,0.000046,0.000054,0.000052,0.000053,0.000052,0.000047,0.000048,0.000055
00:05:00,0.000036,0.000044,0.000054,0.000227,0.000035,0.000052,0.000055,0.000043,0.000059,0.000057,...,0.000222,0.000045,0.000046,0.000054,0.000052,0.000053,0.000052,0.000047,0.000048,0.000055
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23:56:00,0.000036,0.001136,0.000548,0.000048,0.000347,0.000052,0.000055,0.003395,0.000281,0.000169,...,0.000049,0.000472,0.000046,0.000054,0.000310,0.000053,0.000217,0.000047,0.000048,0.000055
23:57:00,0.000036,0.001136,0.000548,0.000048,0.000347,0.000052,0.000055,0.003395,0.000281,0.000169,...,0.000049,0.000407,0.000046,0.000054,0.000310,0.000053,0.000544,0.000047,0.000048,0.000055
23:58:00,0.000036,0.000982,0.000561,0.000048,0.000347,0.000052,0.000055,0.003395,0.000281,0.000169,...,0.000049,0.000407,0.000046,0.000054,0.000310,0.000053,0.000544,0.000047,0.000048,0.000055
23:59:00,0.000036,0.000982,0.000471,0.000048,0.000347,0.000052,0.000055,0.003395,0.000281,0.000169,...,0.000049,0.000407,0.000046,0.000054,0.000310,0.000053,0.000544,0.000047,0.000048,0.000055
24:00:00,0.000036,0.001042,0.000504,0.000048,0.000347,0.000052,0.000055,0.000561,0.000281,0.000057,...,0.000049,0.000407,0.000046,0.000054,0.000310,0.000053,0.000544,0.000047,0.000048,0.000055

In [ ]:
net_off_peak_1 = nw.ieee_european_lv_asymmetric('off_peak_1')
net_on_peak_566 = nw.ieee_european_lv_asymmetric('on_peak_566')
net_off_peak_1440 = nw.ieee_european_lv_asymmetric('off_peak_1440')
try:
    pp.runpp_3ph(net_off_peak_1)
    print('runnpp_3ph on net_off_peak_1 successful!')
    pp.runpp_3ph(net_on_peak_566)
    print('runnpp_3ph on net_on_peak_566 successful!')
    pp.runpp_3ph(net_off_peak_1440)
    print('runnpp_3ph on net_off_peak_1440 successful!')
except Exception as e:
    print(e)

runnpp_3ph on net_off_peak_1 successful!
runnpp_3ph on net_on_peak_566 successful!
runnpp_3ph on net_off_peak_1440 successful!

In [43]:
from copy import deepcopy
import create_basic_network as cbn
import pandapower.control as ppc
# print(cbn.net)
net = deepcopy(cbn.net)
pp.runpp_3ph(net, init='auto', max_iteration=100, tolerance_mva=1e-5, calc_voltage_angles=True, v_debug=True)

for _, row in loads.iterrows():
    bus_id = math.floor(row['Bus'])
    pa = qa = pb = qb = pc = qc = 0

    if (bus_id in net.bus.name) and (row['phases'] in {'A', 'B', 'C'}):
        if row['phases'] == 'A':
            pa = row['kW']
            qa = row['kW'] * np.tan(np.arccos(row['PF']))
        elif row['phases'] == 'B':
            pb = row['kW']
            qb = row['kW'] * np.tan(np.arccos(row['PF']))
        else:  # 'C'
            pc = row['kW']
            qc = row['kW'] * np.tan(np.arccos(row['PF']))

        load = pp.create_asymmetric_load(
            net, bus=net.bus.index[net.bus.name == bus_id][0],
            p_a_mw=pa / 1000, q_a_mvar=qa / 1000,
            p_b_mw=pb / 1000, q_b_mvar=qb / 1000,
            p_c_mw=pc / 1000, q_c_mvar=qc / 1000,
            name=row['Name']
        )

        # Attach ConstControl
        phase = row['phases'].lower()
        ppc.ConstControl(
            net, element_index=load,
            variable=f"p_{phase}_mw",
            element="asymmetric_load",
            profile_name=row['Name'], data_source=ds
        )

orig_bus = net.asymmetric_load.bus
net.asymmetric_load = net_off_peak_1440.asymmetric_load
net.asymmetric_load.bus = orig_bus
net.asymmetric_load

,name,bus,p_a_mw,q_a_mvar,p_b_mw,q_b_mvar,p_c_mw,q_c_mvar,sn_mva,scaling,in_service,type,description,sernum,for_name,chr_name
0,LOAD1,5,0.000036,0.000012,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
1,LOAD2,7,0.000000,0.000000,0.001042,3.424888e-07,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
2,LOAD3,10,0.000504,0.000166,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
3,LOAD4,11,0.000048,0.000016,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
4,LOAD5,12,0.000347,0.000114,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
5,LOAD6,13,0.000000,0.000000,0.000052,1.709157e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
6,LOAD7,21,0.000000,0.000000,0.000055,1.807763e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
7,LOAD8,25,0.000000,0.000000,0.000000,0.000000e+00,0.000561,1.843918e-07,NaN,1.0,True,wye,,,,
8,LOAD9,26,0.000281,0.000092,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
9,LOAD10,29,0.000000,0.000000,0.000057,1.873499e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
10,LOAD11,30,0.000000,0.000000,0.000049,1.610552e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
11,LOAD12,33,0.000000,0.000000,0.000000,0.000000e+00,0.000469,1.541528e-07,NaN,1.0,True,wye,,,,
12,LOAD13,34,0.000000,0.000000,0.000056,1.840631e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
13,LOAD14,37,0.000210,0.000069,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
14,LOAD15,39,0.000000,0.000000,0.000053,1.742026e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
15,LOAD16,40,0.000000,0.000000,0.000000,0.000000e+00,0.000052,1.709157e-08,NaN,1.0,True,wye,,,,
16,LOAD17,42,0.000000,0.000000,0.000000,0.000000e+00,0.000048,1.577684e-08,NaN,1.0,True,wye,,,,
17,LOAD18,45,0.000000,0.000000,0.000000,0.000000e+00,0.000049,1.610552e-08,NaN,1.0,True,wye,,,,
18,LOAD19,46,0.000000,0.000000,0.000000,0.000000e+00,0.000053,1.742026e-08,NaN,1.0,True,wye,,,,
19,LOAD20,47,0.000051,0.000017,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
20,LOAD21,49,0.000045,0.000015,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
21,LOAD22,50,0.000054,0.000018,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
22,LOAD23,52,0.000000,0.000000,0.000604,1.985252e-07,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
23,LOAD24,54,0.000000,0.000000,0.000000,0.000000e+00,0.000054,1.774894e-08,NaN,1.0,True,wye,,,,
24,LOAD25,57,0.000050,0.000016,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
25,LOAD26,60,0.000000,0.000000,0.000034,1.117526e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
26,LOAD27,62,0.000000,0.000000,0.000000,0.000000e+00,0.000155,5.094603e-08,NaN,1.0,True,wye,,,,
27,LOAD28,64,0.000000,0.000000,0.000000,0.000000e+00,0.000028,9.203155e-09,NaN,1.0,True,wye,,,,
28,LOAD29,66,0.000823,0.000271,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
29,LOAD30,67,0.000053,0.000017,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
30,LOAD31,72,0.000182,0.000060,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
31,LOAD32,73,0.000000,0.000000,0.000000,0.000000e+00,0.000056,1.840631e-08,NaN,1.0,True,wye,,,,
32,LOAD33,75,0.000000,0.000000,0.000000,0.000000e+00,0.000250,8.217103e-08,NaN,1.0,True,wye,,,,
33,LOAD34,76,0.000176,0.000058,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
34,LOAD35,77,0.000000,0.000000,0.000043,1.413342e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
35,LOAD36,80,0.000000,0.000000,0.000055,1.807763e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
36,LOAD37,81,0.000000,0.000000,0.000045,1.479078e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
37,LOAD38,83,0.000000,0.000000,0.000228,7.493998e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
38,LOAD39,87,0.000000,0.000000,0.000000,0.000000e+00,0.000048,1.577684e-08,NaN,1.0,True,wye,,,,
39,LOAD40,88,0.000000,0.000000,0.000043,1.413342e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
40,LOAD41,93,0.000000,0.000000,0.000196,6.442208e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
41,LOAD42,95,0.000000,0.000000,0.000000,0.000000e+00,0.000054,1.774894e-08,NaN,1.0,True,wye,,,,
42,LOAD43,96,0.000000,0.000000,0.000000,0.000000e+00,0.000050,1.643420e-08,NaN,1.0,True,wye,,,,
43,LOAD44,97,0.000000,0.000000,0.000029,9.531839e-09,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
44,LOAD45,102,0.000000,0.000000,0.000657,2.159455e-07,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
45,LOAD46,103,0.000049,0.000016,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
46,LOAD47,104,0.000000,0.000000,0.000000,0.000000e+00,0.000407,1.337744e-07,NaN,1.0,True,wye,,,,
47,LOAD48,106,0.000046,0.000015,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
48,LOAD49,107,0.000054,0.000018,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
49,LOAD50,110,0.000000,0.000000,0.000310,1.018921e-07,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
50,LOAD51,112,0.000053,0.000017,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
51,LOAD52,113,0.000544,0.000179,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
52,LOAD53,114,0.000000,0.000000,0.000047,1.544815e-08,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
53,LOAD54,115,0.000048,0.000016,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,
54,LOAD55,116,0.000055,0.000018,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,1.0,True,wye,,,,

In [45]:
pp.runpp_3ph(net, init='auto', max_iteration=100, tolerance_mva=1e-5, calc_voltage_angles=True, v_debug=True)
to_json(net, os.path.join(main_dir, 'json_networks', "full_load_network.json"))